# Generated by Django 5.2 on 2025-04-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contract_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-contract_date',)},
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('note', models.TextField(default=' ')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='app.contract')),
            ],
        ),
    ]
