# Generated by Django 5.2 on 2025-04-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contract_options_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
