# Generated by Django 5.2 on 2025-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contract_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
