# Generated by Django 5.2 on 2025-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='employee_name',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
