# Generated by Django 5.2 on 2025-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_deliverable_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_header_image',
            field=models.ImageField(default='logo.jpg', upload_to='contracts'),
        ),
    ]
