# Generated by Django 5.2 on 2025-05-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_expensses_contract_is_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='app.contract'),
        ),
    ]
